apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/RoshanChaturpale/argo-repo-Kubernates.git
    targetRevision: HEAD
    path: dev

  destination:
    server: https://kubernetes.default.svc
    namespace: my-first-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
